name: Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  IMAGE_NAME: rectx
  TAG_LATEST: latest

jobs:
  amd:
    name: AMD build
    if: ${{ github.event_name != 'push' || vars.DOCKER_ON == 1 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: pierreraffa/cancel-previous-runs-action@1.11
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
          platforms: linux/amd64
          push: false
  arm:
    name: ARM build
    if: ${{ github.event_name != 'push' || vars.DOCKER_ON == 1 }}
    runs-on: macos-13
    permissions: write-all
    steps:
      - uses: pierreraffa/cancel-previous-runs-action@1.11
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: douglascamata/setup-docker-macos-action@v1
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
          platforms: linux/arm64
          push: false