name: Container

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
    branches: [ main ]

env:
  TAG_LATEST: latest
  REGISTRY_IMAGE: rectx

jobs:
  container:
    name: build
    if: ${{ github.event_name != 'push' || vars.DOCKER_ON == 1 }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.REGISTRY_IMAGE }}-${{ env.PLATFORM_PAIR }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REGISTRY_IMAGE }}-${{ env.PLATFORM_PAIR }}.tar
          path: ${{ runner.temp }}/${{ env.REGISTRY_IMAGE }}-${{ env.PLATFORM_PAIR }}.tar