name: Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  IMAGE_NAME: rectx
  TAG_LATEST: latest

jobs:
  container:
    name: Build container
    if: ${{ github.event_name != 'push' || vars.DOCKER_ON == 1 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: pierreraffa/cancel-previous-runs-action@1.11
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker buildx build . \
          --tag ${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }} \
          --platform linux/amd64,linux/arm64

