name: Container

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  TAG_LATEST: latest
  IMAGE_NAME: rectx

jobs:
  container:
    name: Docker build
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          #-linux/arm64
    steps:
      - uses: pierreraffa/cancel-previous-runs-action@1.11
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
