name: "Runtime Test"

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    name: Runtime test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -q -r requirements.txt
      - run: make results/l_003.dig
      - run: cat results/l_003.dig