name: "Runtime Test"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:
    branches: [ main ]

jobs:
  test:
    name: Runtime test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -q -r requirements.txt
      - run: time make TO=60 SZ=10
      - run: cat results/_results.txt
      - name: report
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/_log.txt
            results/_results.txt
          compression-level: 0
